// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9-4RJ4Ur33LVW8xo6ChIG7pXaEx1fjUI',
    appId: '1:933707774940:web:d5af659606d01521a56d19',
    messagingSenderId: '933707774940',
    projectId: 'aplikasi-omah',
    authDomain: 'aplikasi-omah.firebaseapp.com',
    storageBucket: 'aplikasi-omah.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHeLJfhVEl5cufsgfVrynxyXQhovGrcus',
    appId: '1:933707774940:android:79d41406193eb8a5a56d19',
    messagingSenderId: '933707774940',
    projectId: 'aplikasi-omah',
    storageBucket: 'aplikasi-omah.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoVCUMAA5PbLP4PbAmXITzH-VACbQmK9s',
    appId: '1:933707774940:ios:2a3d7f896ff7ff9fa56d19',
    messagingSenderId: '933707774940',
    projectId: 'aplikasi-omah',
    storageBucket: 'aplikasi-omah.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiOmah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoVCUMAA5PbLP4PbAmXITzH-VACbQmK9s',
    appId: '1:933707774940:ios:2a3d7f896ff7ff9fa56d19',
    messagingSenderId: '933707774940',
    projectId: 'aplikasi-omah',
    storageBucket: 'aplikasi-omah.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiOmah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9-4RJ4Ur33LVW8xo6ChIG7pXaEx1fjUI',
    appId: '1:933707774940:web:e22200d05176e701a56d19',
    messagingSenderId: '933707774940',
    projectId: 'aplikasi-omah',
    authDomain: 'aplikasi-omah.firebaseapp.com',
    storageBucket: 'aplikasi-omah.firebasestorage.app',
  );
}
